version: "3"
services:
  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
        MYSQL_DATABASE: equiplano-seg
        MYSQL_USER: appuser
        MYSQL_PASSWORD: appuser
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - equiplano-network
      
  equiplano-backservice:
    image: isedsonadriano/equiplanobackend:latest
    ports:
      - "8085:8085"
    networks:
      - equiplano-network
    depends_on:
      - mysqldb
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/equiplano-seg?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
     SPRING_DATASOURCE_USERNAME: appuser
     SPRING_DATASOURCE_PASSWORD: appuser    
  

volumes:
  db-data:
 
networks:
  equiplano-network:
    driver: bridge